### ISSUE TITLE
Exception when using more than 15 bards.

### ISSUE THREAD

**Issue by Meowchestra** [BardMusicPlayer/BardMusicPlayer#39]
BMP throws out this exception when using more than 15 bards when you hit play. If you have 15 bards exactly (or less), no error. If you have over 15 bards (16 - 21), error on play. Doubt anyone but me would even attempt or be using this many bards, but figured I'd let you know about the error anyways. Moogle says it's a Sanford bug.

```
************** Exception Text **************
Sanford.Multimedia.Timers.TimerStartException: Unable to start multimedia Timer.
   at Sanford.Multimedia.Timers.Timer.Start()
   at Sanford.Multimedia.Midi.MidiInternalClock.Continue()
   at FFBardMusicPlayer.BmpCustomSequencer.Play()
   at FFBardMusicPlayer.Controls.BmpLocalPerformer.Play(Boolean play)
   at FFBardMusicPlayer.Controls.BmpLocalOrchestra.PerformerPlay(Boolean play)
   at FFBardMusicPlayer.Forms.BmpMain.OnPlayStatusChange(Object o, Boolean playing)
   at FFBardMusicPlayer.BmpCustomSequencer.OnPlayStatusChange(EventArgs e)
   at FFBardMusicPlayer.BmpCustomSequencer.Play()
   at System.Windows.Forms.Control.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ButtonBase.WndProc(Message& m)
   at System.Windows.Forms.Button.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
```

**Comment by troy-f** [comment]
Closing as this won't be an issue in 2.0
